baseURL: https://sanskriti-bajaj-portfolio-website.netlify.app
languageCode: en-us
title: Portfolio website Sanskriti
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Checkout all my Data Analytics projects on this website
    title: Portfolio website for Sanskriti Bajaj
  Linkedin: https://www.linkedin.com/in/sb1998/
  contact: 
    address:
      - city: City, ST 00000
        country: Country
        street: Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sanskriti.bajaj98@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: 07842641293
        title: Mobile
  custom_css: []
  custom_js: []
  description: Hi thank you for checking out my website. I am a Masters in Financial Analysis student at London Business School
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Finance-Banner-768x377.png
        subtitle: Macro-Factor investing model developed for my summer internship at Quantech Capital
        title: Factor Investing Model using Python
        url: https://github.com/SanskritiBajaj98/FactorInvestingModel/blob/main/Quantech%20Capital%20Internship%20presentation%20-%20Sanskriti%20Bajaj%20.pdf
      - image: santander-cycles-bike-share-sharing.jpeg
        subtitle: Completed as part of my nanodegree in partnership with Udacity
        title: US Bike Share Data Analysis
        url: https://github.com/SanskritiBajaj98/USBikeshareSystemDataAnalysis/blob/master/Bike_Share_Analysis.ipynb
      - image: LEM_fire_sensor-1028x579.jpeg
        subtitle: Undertook a project to predict forest fires
        title: Predicting Forest Fires 
        url: https://github.com/SanskritiBajaj98/ForestFiresMLAnalysis/blob/master/Sanskriti_ForestFires.ipynb
      - image: jbfWuj3RSAAvmJeBwLWbsw.jpeg
        subtitle: Used Tableau for analysing movie data as part of the Business Analyst Nanodegree undertaken in partnership with Udacity
        title: Analysis of Movies dataset using Tableau
        url: https://github.com/SanskritiBajaj98/BusinessAnalystNanodegree/blob/master/TableauProject.pdf
      - image: AlteryxBanner.jpeg
        subtitle: Conducted AB testing for a menu launch analysis using Alteryx
        title: AB Testing Using Alteryx
        url: https://github.com/SanskritiBajaj98/BusinessAnalystNanodegree/blob/master/ABTesting.pdf
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
