baseURL: https://sanskriti-bajaj-portfolio-website.netlify.app
languageCode: en-us
title: Portfolio website Sanskriti
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Checkout all my Data Analytics projects on this website
    title: Data Analytics by Sanskriti Bajaj
  Linkedin: https://www.linkedin.com/in/sb1998/
  contact: 
    address:
      - city: London
        country: United Kingdom
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sanskriti.bajaj98@gmail.com
        title: Email
    enable: yes
    phone:
      - phone:  0447842641293
        title: Mobile
  custom_css: []
  custom_js: []
  description: Hi thank you for checking out my website. I am a Masters in Financial Analysis student at London Business School
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sanskriti Bajaj
    enable: yes
    quicklinks:
      - alt: London Business School
        text: 'Designed at: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/sanskritibajaj
      - icon: fa-github
        label: GitHub
        url: https://github.com/SanskritiBajaj98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sb1998/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Explore more
        url: blogs
      - name: Home
        url: '#'
    menu: Menu
    subtitle: Sanskriti Bajaj
    title: Designed by
  tiles:
    enable: yes
    showcase:
      - image: MyschoolImage.png
        subtitle: Find out more about my background
        title: About me
        url: https://www.linkedin.com/in/sb1998/
      - image: Finance-Banner-768x377.png
        subtitle: Macro-Factor investing model developed for my summer internship at Quantech Capital
        title: Factor Investing Model using Python
        url: blogs/QuantechCapital.pdf
      - image: rstudio-vector-logo.png
        subtitle: Completed as part of pre-programme course 
        title: Pre-programme assignment in Data Analytics 
        url: blogs/Sanskriti_Bajaj.Rmd
      - image: LEM_fire_sensor-1028x579.jpeg
        subtitle: Undertook a project to predict forest fires
        title: Predicting Forest Fires 
        url: blogs/Predicting Forest Fires.pdf
      - image: jbfWuj3RSAAvmJeBwLWbsw.jpeg
        subtitle: Used Tableau for analysing movie data as part of the Business Analyst Nanodegree undertaken in partnership with Udacity
        title: Analysis of Movies dataset using Tableau
        url: blogs/TableauProject.pdf
      - image: AlteryxBanner.jpeg
        subtitle: Conducted AB testing for a menu launch analysis using Alteryx
        title: AB Testing Using Alteryx
        url: blogs/ABTesting.pdf
  two:
    buttonText: Connnect 
    enable: yes
    subtitle: " Sanskriti Bajaj is currently pursuing her Masters in Financial Analysis at London Business School. 
      \n Prior to joining London Business School, Sanskriti has worked with three diverse organizations over the course of the last two years. \n     
    Sanskriti began her career journey by completing an internship with the Govt. of India, whereby she was part of the team heading the $1 Trillion Asset Monetization Program. \n    
    She then took on the role of a Data Analyst at The Economist Group. As part of The Economist's Intelligence Unit, she designed econometric models for producing data forecasts. \n    
    Prior to joining London Business School, Sanskriti undertook an internship with a quantitative investing start-up where she designed a Macro-Factor Investing model using Python which was used for creating a new investment vehicle for retail investors. \n Sanskriti is passionate about using Data for making efficient investment decisions for clients. Reach out to her for collborating on internesting Data Analytics projects."
    title: Career summary
    url: https://www.linkedin.com/in/sb1998/
